---
title: "To Do
---

* Invert scores: 4, 6, 8, 9, 11, 13, 15, 18, 20, 21.

* Match questions asked to question number via: Altemeyer, Bob (2007). The Authoritarians. University of Manitoba.

* Recode education: 1=Less than high school, 2=High school, 3=University degree, 4=Graduate degree

* Recode hand: 1=Right, 2=Left, 3=Both

* Recode religion: 1=Agnostic, 2=Atheist, 3=Buddhist, 4=Christian (Catholic), 5=Christian (Mormon), 6=Christian (Protestant), 7=Christian (Other), 8=Hindu, 9=Jewish, 10=Muslim, 11=Sikh, 12=Other

* Recode orientation: 1=Heterosexual, 2=Bisexual, 3=Homosexual, 4=Asexual, 5=Other

* Recode voted: 1=Yes, 2=No

* Recode married: 1=Never married, 2=Currently married, 3=Previously married

* Recode TIPIs
TIPI1	Extraverted, enthusiastic.
TIPI2	Critical, quarrelsome.
TIPI3	Dependable, self-disciplined.
TIPI4	Anxious, easily upset.
TIPI5	Open to new experiences, complex.
TIPI6	Reserved, quiet.
TIPI7	Sympathetic, warm.
TIPI8	Disorganized, careless.
TIPI9	Calm, emotionally stable.
TIPI10	Conventional, uncreative.

The TIPI items were rated "I see myself as:" _____ such that

1 = Disagree strongly
2 = Disagree moderately
3 = Disagree a little
4 = Neither agree nor disagree
5 = Agree a little
6 = Agree moderately
7 = Agree strongly